# Generated by Django 3.2 on 2022-02-12 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('favourite_game', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user_picture', models.ImageField(blank=True, default='uploads/default.png', upload_to='uploads/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile_created', models.DateField(default=django.utils.timezone.now)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], default=None, max_length=8)),
                ('friend_created', models.DateField(default=django.utils.timezone.now)),
                ('friend_updated', models.DateField(default=django.utils.timezone.now)),
                ('friend_receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend_receiver', to='profiles.userprofile')),
                ('friend_sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friend_sender', to='profiles.userprofile')),
            ],
        ),
    ]
