# Generated by Django 3.2 on 2022-02-04 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
        migrations.DeleteModel(
            name='UserPicture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(default='default-pic.png', upload_to='uploads/'),
        ),
    ]
