# Generated by Django 3.2 on 2022-02-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
