# Generated by Django 3.2 on 2022-02-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220205_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(default='default-image.png', upload_to='media/uploads'),
        ),
    ]
