# Generated by Django 3.2 on 2022-02-25 23:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/diaand2n5/image/upload/v1644080414/uploads/default-image_rw2t7w.png', max_length=255, verbose_name='image'),
        ),
    ]
