# Generated by Django 3.2 on 2022-02-05 14:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_userprofile_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='default-image.png'),
        ),
    ]
