# Generated by Django 3.2 on 2022-02-06 16:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user'),
        ),
    ]
