# Generated by Django 3.2 on 2022-02-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
