# Generated by Django 3.2 on 2022-02-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_post_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_picture',
            new_name='post_picture',
        ),
    ]
