# Generated by Django 3.2 on 2022-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0010_auto_20220222_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
